name: Auto Create Release

on:
  push:
    tags:
      - 'v*.*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from tag
        id: get_version
        run: |
          echo "VERSION=$(git describe --tags)" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: |
            {
              "categories": [
                {
                  "title": "## 🚀 新功能",
                  "labels": ["feature", "enhancement"]
                },
                {
                  "title": "## 🐛 Bug 修复",
                  "labels": ["bug", "fix"]
                },
                {
                  "title": "## 📝 文档更新",
                  "labels": ["documentation"]
                },
                {
                  "title": "## 🔨 其他更改",
                  "labels": []
                }
              ],
              "template": "#{{CHANGELOG}}\n\n## 📦 Commits\n\n{{COMMITS}}\n\n## ⚡️ PR 列表\n\n{{PULL_REQUESTS}}\n",
              "pr_template": "- #{{NUMBER}} {{TITLE}}",
              "empty_template": "- 无更新",
              "max_tags_to_fetch": 200,
              "max_pull_requests": 200,
              "max_back_track_time_days": 90
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }} 